language: nix

before_install:
  - nix-channel --update
  - echo "trusted-users = root travis" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use miso-haskell
